apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-frontend
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-frontend
  template:
    metadata:
      labels:
        app: youtube-frontend
    spec:
      containers:
        - name: frontend
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/youtube-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
