apiVersion: v1
kind: Service
metadata:
  name: youtube-frontend-service
  namespace: youtube
spec:
  type: ClusterIP
  selector:
    app: youtube-frontend
  ports:
    - port: 80
      targetPort: 80
